'use client'

import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import ParticleBackground from '@/components/ParticleBackground'
import CommonCTA from '@/components/CommonCTA'
import BackToTop from '@/components/BackToTop'
import { motion } from 'framer-motion'
import { 
  AlertTriangle,
  Shield,
  FileText,
  CheckCircle,
  Info
} from 'lucide-react'

const disclaimerSections = [
  {
    title: 'Medical Device Disclaimer',
    content: 'The EEG systems, bio-integrated sensors, and neurotechnology products offered by Sentient Biotech Private Limited are designed for research, clinical, and professional use. These devices are not intended for self-diagnosis or treatment of medical conditions. Users should consult with qualified healthcare professionals before making any medical decisions based on data from our devices.',
    icon: AlertTriangle
  },
  {
    title: 'Defense and Aerospace Applications',
    content: 'Products designed for defense and aerospace applications, including the Starscream pilot headgear, are intended for use by qualified military personnel and certified aviation professionals only. These systems are not approved for civilian aviation use without proper certification and training.',
    icon: Shield
  },
  {
    title: 'Research and Development',
    content: 'Some technologies described on this website are in various stages of research and development. Performance specifications, capabilities, and availability may change as products evolve. Sentient Biotech reserves the right to modify product features and specifications without prior notice.',
    icon: FileText
  },
  {
    title: 'Data Privacy and Security',
    content: 'While Sentient Biotech implements industry-standard security measures to protect neural and biometric data, users acknowledge that no system is completely secure. Users are responsible for ensuring compliance with applicable data protection regulations in their jurisdiction.',
    icon: Shield
  },
  {
    title: 'Intellectual Property',
    content: 'All technologies, algorithms, software, and proprietary methods described on this website are protected by intellectual property rights. Unauthorized use, reproduction, or distribution of Sentient Biotech\'s proprietary technology is strictly prohibited.',
    icon: FileText
  },
  {
    title: 'Limitation of Liability',
    content: 'Sentient Biotech Private Limited shall not be liable for any direct, indirect, incidental, special, or consequential damages arising from the use of our products or services. Users assume full responsibility for the appropriate use and interpretation of data generated by our systems.',
    icon: AlertTriangle
  }
]

const complianceInfo = [
  'Compliance with IEC 60601 medical device standards',
  'Adherence to ISO 13485 quality management systems',
  'GDPR and HIPAA data protection compliance',
  'Indian medical device regulations compliance',
  'Defense-grade security protocols implementation'
]

export default function DisclaimerPage() {
  return (
    <main className="relative min-h-screen bg-deep-indigo">
      <ParticleBackground />
      <Navbar />
      <BackToTop />
      
      {/* Hero Section */}
      <section className="relative pt-24 sm:pt-32 pb-16 sm:pb-20 overflow-hidden">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, ease: [0.4, 0, 0.2, 1] }}
            className="text-center"
          >
            <motion.div 
              initial={{ scale: 0.9, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              transition={{ duration: 0.6, delay: 0.2 }}
              className="mb-6"
            >
              <div className="inline-block">
                <AlertTriangle className="w-20 h-20 mx-auto mb-6 text-electric-cyan" />
              </div>
            </motion.div>
            
            <h1 className="text-4xl sm:text-5xl md:text-6xl lg:text-7xl font-display font-bold gradient-text mb-4 sm:mb-6">
              Disclaimer
            </h1>
            <p className="text-base sm:text-lg text-text-secondary max-w-3xl mx-auto px-4">
              Important legal information regarding the use of Sentient Biotech products and services
            </p>
          </motion.div>
        </div>
      </section>

      {/* Introduction */}
      <section className="py-16 sm:py-20 bg-glass-white backdrop-blur-sm">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            viewport={{ once: true }}
            className="max-w-5xl mx-auto"
          >
            <div className="glass-panel-strong rounded-2xl p-8 md:p-12">
              <div className="flex items-start gap-4 mb-6">
                <Info className="w-8 h-8 text-electric-cyan flex-shrink-0 mt-1" />
                <div>
                  <h2 className="text-2xl sm:text-3xl font-display font-bold text-white mb-4">
                    Important Notice
                  </h2>
                  <p className="text-white/80 text-lg leading-relaxed">
                    This disclaimer outlines important limitations and considerations regarding the use of Sentient Biotech Private Limited's products and services. Please read this information carefully before using any of our technologies.
                  </p>
                </div>
              </div>
            </div>
          </motion.div>
        </div>
      </section>

      {/* Disclaimer Sections */}
      <section className="py-16 sm:py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            viewport={{ once: true }}
            className="text-center mb-12 sm:mb-16"
          >
            <h2 className="text-2xl sm:text-3xl lg:text-4xl font-display font-bold text-text-primary mb-4">
              Legal Disclaimers
            </h2>
            <p className="text-sm sm:text-base text-text-secondary max-w-3xl mx-auto px-4">
              Comprehensive information about product usage, limitations, and legal considerations
            </p>
          </motion.div>
          
          <div className="space-y-8">
            {disclaimerSections.map((section, index) => (
              <motion.div
                key={section.title}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ delay: index * 0.1, duration: 0.5 }}
                viewport={{ once: true }}
                className="glass-panel-strong rounded-2xl p-8"
              >
                <div className="flex items-start gap-6">
                  <div className="w-16 h-16 bg-gradient-to-br from-primary-blue to-secondary-blue rounded-xl flex items-center justify-center flex-shrink-0">
                    <section.icon className="w-8 h-8 text-white" />
                  </div>
                  <div className="flex-1">
                    <h3 className="text-xl sm:text-2xl font-display font-bold text-white mb-4">
                      {section.title}
                    </h3>
                    <p className="text-white/80 leading-relaxed">
                      {section.content}
                    </p>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Compliance Information */}
      <section className="py-16 sm:py-20 bg-glass-white backdrop-blur-sm">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            viewport={{ once: true }}
            className="text-center mb-12"
          >
            <h2 className="text-2xl sm:text-3xl lg:text-4xl font-display font-bold text-text-primary mb-4">
              Compliance and Standards
            </h2>
            <p className="text-sm sm:text-base text-text-secondary max-w-3xl mx-auto px-4">
              Sentient Biotech adheres to international standards and regulatory requirements
            </p>
          </motion.div>
          
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.2 }}
            viewport={{ once: true }}
            className="glass-panel-strong rounded-2xl p-8 md:p-12"
          >
            <div className="grid md:grid-cols-2 gap-6">
              {complianceInfo.map((item, index) => (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, x: -20 }}
                  whileInView={{ opacity: 1, x: 0 }}
                  transition={{ delay: index * 0.1, duration: 0.5 }}
                  viewport={{ once: true }}
                  className="flex items-center gap-4"
                >
                  <CheckCircle className="w-6 h-6 text-electric-cyan flex-shrink-0" />
                  <span className="text-white/80">{item}</span>
                </motion.div>
              ))}
            </div>
          </motion.div>
        </div>
      </section>

      {/* Contact Information */}
      <section className="py-16 sm:py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            viewport={{ once: true }}
            className="glass-panel-strong rounded-2xl p-8 md:p-12 text-center"
          >
            <h2 className="text-2xl sm:text-3xl font-display font-bold text-white mb-6">
              Questions or Concerns?
            </h2>
            <p className="text-white/80 text-lg mb-8 max-w-3xl mx-auto">
              If you have any questions about this disclaimer or need clarification about the appropriate use of our products, please contact our legal team.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <motion.a
                href="/contact"
                whileHover={{ scale: 1.02, y: -2 }}
                whileTap={{ scale: 0.98 }}
                className="inline-flex items-center gap-2 bg-gradient-to-r from-primary-blue to-secondary-blue text-white px-6 py-3 rounded-xl font-semibold transition-all duration-200 hover:shadow-blue-lg"
              >
                Contact Legal Team
              </motion.a>
              <motion.a
                href="/support"
                whileHover={{ scale: 1.02, y: -2 }}
                whileTap={{ scale: 0.98 }}
                className="inline-flex items-center gap-2 border border-primary-blue text-primary-blue px-6 py-3 rounded-xl font-semibold transition-all duration-200 hover:bg-primary-blue hover:text-white"
              >
                Technical Support
              </motion.a>
            </div>
          </motion.div>
        </div>
      </section>

      <CommonCTA />
      <Footer />
    </main>
  )
}
